name: rick_and_morty_api
description: Dart wrapper for The Rick and Morty API
version: 0.1.2
homepage: https://github.com/Yash-Garg/RickandMorty-Dart-Wrapper

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  lints: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
